apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-provisioner
  template:
    metadata:
      labels:
        app: cloud-provisioner
    spec:
      nodeSelector:
        kubernetes.io/hostname: virtual-158-4-2
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        effect: "NoSchedule"
      serviceAccountName: rbac-mck8s
      containers:
      - image: eu.gcr.io/inlaid-index-271509/cloudprovisioner
        name: cloud-provisioner
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /root/.kube/config
          name: kube-config
        #resources:
        #  requests:
        #    cpu: 1000m
        #    memory: 1024Mi
      volumes:
      - name: kube-config
        hostPath:
          path: /root/.kube/config
          type: File

