apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiclusterscheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiclusterscheduler
  template:
    metadata:
      labels:
        app: multiclusterscheduler
    spec:
      serviceAccountName: rbac-mck8s
      containers:
      - image: mck8s-scheduler
        name: mcs
        imagePullPolicy: IfNotPresent
        - env:
          - name: PYTHONUNBUFFERED
            value: "0"
          - name: PROMETHEUS_DEMO_SERVICE_SERVICE_HOST
            value: 8.46.188.21
          - name: PROMETHEUS_DEMO_SERVICE_SERVICE_PORT
            value: "30003"
        volumeMounts:
        - mountPath: /root/.kube/config
          name: kube-config
        #resources:
        #  requests:
        #    cpu: 1
        #    memory: 1024Mi
      volumes:
      - name: kube-config
        hostPath:
          path: /root/.kube/config
          type: File

