apiVersion: apps/v1
kind: Deployment
metadata:
  name: mchpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mchpa
  template:
    metadata:
      labels:
        app: mchpa
    spec:
      serviceAccountName: rbac-mck8s
      containers:
      - image: mck8s-autoscaler
        name: mchpa
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /root/.kube/config
          name: kube-config
        #resources:
        #  requests:
        #    cpu: 1000m
        #    memory: 1024Mi
      volumes:
      - name: kube-config
        hostPath:
          path: /root/.kube/config
          type: File
